@startuml

solution43->WebsiteGenerator

class solution43

class solution43 {
-siteName; String
-authorName; String
-javaScriptFiles; String
-ccsFiles; String
-currentPath; String

+main(); void
-nameStringInputs(); void
-filesGenerator(); void

}

class WebsiteGenerator{
+newWebsite; File

+generateWebsiteOutput(); void

}

@enduml