@startuml

class solution43

class solution43 {
-siteName; String
-authorName;String
-javaScriptFiles;String
-ccsFiles;String
-currentPath; String

+main(); void
-nameStringInputs(); void
-filesGenerator(); void

}

class websiteGenerator{
+newWebsite; File

+generateWebsiteOutput(); void

}

@enduml